-- 8/3 14:32
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE IMAGE_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE WISHLIST_SEQ;
DROP SEQUENCE REFUND_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE PRODUCT_SEQ;

DROP TABLE PRODUCT_REVIEW;
DROP TABLE PRODUCT_IMAGE;
DROP TABLE CART;
DROP TABLE WISHLIST;
DROP TABLE REFUND;
DROP TABLE ORDERS;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;

CREATE SEQUENCE REVIEW_SEQ          START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE IMAGE_SEQ           START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE CART_SEQ            START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE WISHLIST_SEQ        START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE REFUND_SEQ          START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE ORDERS_SEQ          START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE MEMBER_SEQ          START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE PRODUCT_SEQ         START WITH 1 MAXVALUE 999999999 INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE PRODUCT (
	PRODUCT_IDX             NUMBER          DEFAULT PRODUCT_SEQ.NEXTVAL PRIMARY KEY,    -- 상품 인덱스
	PARENT_CATECODE		    CHAR(3)         NOT NULL,   -- 상위 카테고리 코드('101' ~ '999'). 상위 카테고리가 없을 시(최상위 카테고리일 시) -> '000'
    CATECODE                CHAR(3)         NOT NULL,   -- 카테고리 코드('101' ~ '999')
    PRODUCT_NAME            VARCHAR2(50)    UNIQUE NOT NULL,    -- 상품명
    PRODUCT_DESC            VARCHAR2(2000)  NOT NULL,   -- 상품 설명
    PRODUCT_LENGTH          NUMBER,                     -- 상품 길이
    PRODUCT_WIDTH           NUMBER,                     -- 상품 너비
    PRODUCT_HEIGHT          NUMBER,                     -- 상품 높이
    PRODUCT_COLOR           VARCHAR2(50)    NOT NULL,   -- 상품 색상
    PRODUCT_STOCK           NUMBER          NOT NULL,   -- 상품 재고
    PRODUCT_SALEQUANTITY    NUMBER          DEFAULT 0,  -- 상품 판매량
    PRODUCT_REGDATE         DATE            DEFAULT SYSDATE     -- 상품 등록일
);

CREATE TABLE MEMBER (
	MEMBER_IDX              NUMBER          DEFAULT MEMBER_SEQ.NEXTVAL PRIMARY KEY,     -- 고객 인덱스
    MEMBER_ID               VARCHAR2(20)    UNIQUE NOT NULL,
    MEMBER_PW               VARCHAR2(20)    NOT NULL,
    MEMBER_NAME             VARCHAR2(20)    NOT NULL,
    MEMBER_BIRTH            DATE            NOT NULL,
    MEMBER_EMAIL            VARCHAR2(40)    NOT NULL,
    MEMBER_PNUM             VARCHAR2(20)    NOT NULL,   -- 전화번호
    MEMBER_ZIPCODE          VARCHAR2(20)    NOT NULL,   -- 우편번호
    MEMBER_ADDRESS          VARCHAR2(100)   NOT NULL,   -- 주소
    MEMBER_GENDER           CHAR(1)         CHECK(MEMBER_GENDER IN ('M', 'F', 'N')) NOT NULL, -- 성별('M' = 남, 'F' = 여, 'N' = 응답거부) 
    MEMBER_REGDATE          DATE            DEFAULT SYSDATE     -- 회원 가입일
);

CREATE TABLE PRODUCT_REVIEW (
    REVIEW_IDX              NUMBER          DEFAULT REVIEW_SEQ.NEXTVAL PRIMARY KEY,     -- 상품 리뷰 인덱스
    PRODUCT_IDX             NUMBER          NOT NULL,   -- FK : 상품 인덱스
    PARENT_REVIEW           NUMBER          NOT NULL,   -- 상위 리뷰 인덱스. 상위 리뷰가 없을 시(최상위 리뷰일 시) -> 0
    REVIEW_WRITER           VARCHAR2(20)    NOT NULL,   -- 리뷰 작성자
    REVIEW_POINT_ASSEMBLY   NUMBER          NOT NULL,   -- 평가 1 : 손쉬운 조립 / 설
    REVIEW_POINT_COSPER     NUMBER          NOT NULL,   -- 평가 2 : 제품 가성비
    REVIEW_POINT_QUALITY    NUMBER          NOT NULL,   -- 평가 3 : 제품 품질
    REVIEW_POINT_SHAPE      NUMBER          NOT NULL,   -- 평가 4 : 제품 외관
    REVIEW_POINT_FUNCTION   NUMBER          NOT NULL,   -- 평가 5 : 제품 기능
    REVIEW_CONTENT          VARCHAR2(2000)  NOT NULL,   -- 리뷰 내용
    REVIEW_COUNT            NUMBER          DEFAULT 0,  -- 리뷰 개수
    REVIEW_REGDATE          DATE            DEFAULT SYSDATE,     -- 리뷰 작성일
    
    CONSTRAINT REVIEW_PRODUCT_FK FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT(PRODUCT_IDX) ON DELETE CASCADE
);

CREATE TABLE PRODUCT_IMAGE (
    IMAGE_IDX               NUMBER          DEFAULT IMAGE_SEQ.NEXTVAL PRIMARY KEY,  -- 상품 이미지 인덱스
    PRODUCT_IDX             NUMBER          NOT NULL,   -- FK : 상품 인덱스
    IMAGE_ORIGINAL_FILENAME VARCHAR2(50)    NOT NULL,   -- 원래 이미지명
    IMAGE_NEW_FILENAME      VARCHAR2(50)    NOT NULL,   -- 새로 만들어 준 이미지명
    IMAGE_FILESIZE          NUMBER          NOT NULL,   -- 파일 크기
    IMAGE_ISTHUMBNAIL       CHAR(1)         CHECK(IMAGE_ISTHUMBNAIL IN ('Y', 'N')) NOT NULL,    -- 대표 이미지인가? ('Y' OR 'N')
    IMAGE_REGDATE           DATE            DEFAULT SYSDATE,     -- 이미지 등록일
    
    CONSTRAINT IMAGE_PRODUCT_FK FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT(PRODUCT_IDX) ON DELETE CASCADE
);

CREATE TABLE CART (
    CART_IDX                NUMBER          DEFAULT CART_SEQ.NEXTVAL PRIMARY KEY,   -- 카트(에 담은 상품) 인덱스
    PRODUCT_IDX             NUMBER          NOT NULL,   -- FK : 상품 인덱스
    MEMBER_IDX              NUMBER          NOT NULL,   -- FK : 고객 인덱스
    CART_COUNT              NUMBER          NOT NULL,   -- 해당 상품 수량
    CART_REGDATE            DATE            DEFAULT SYSDATE,    -- 카트에 상품을 추가한 날
    
    CONSTRAINT CART_PRODUCT_FK FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT(PRODUCT_IDX) ON DELETE CASCADE,
    CONSTRAINT CART_MEMBER_FK FOREIGN KEY(MEMBER_IDX) REFERENCES MEMBER(MEMBER_IDX) ON DELETE CASCADE
);

CREATE TABLE WISHLIST (
    WISHLIST_IDX            NUMBER          DEFAULT WISHLIST_SEQ.NEXTVAL PRIMARY KEY,   -- 위시리스트(에 담은 상품) 인덱스
    PRODUCT_IDX             NUMBER          NOT NULL,   -- FK : 상품 인덱스
    MEMBER_IDX              NUMBER          NOT NULL,   -- FK : 고객 인덱스
    WISHLIST_COUNT          NUMBER          NOT NULL,   -- 해당 상품 수량
    WISHLIST_REGDATE        DATE            DEFAULT SYSDATE,    -- 위시리스트에 상품을 추가한 날
    
    CONSTRAINT WISHLIST_PRODUCT_FK FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT(PRODUCT_IDX) ON DELETE CASCADE,
    CONSTRAINT WISHLIST_MEMBER_FK FOREIGN KEY(MEMBER_IDX) REFERENCES MEMBER(MEMBER_IDX) ON DELETE CASCADE
);

CREATE TABLE ORDERS (
    ORDERS_IDX              NUMBER          DEFAULT ORDERS_SEQ.NEXTVAL PRIMARY KEY,     -- 주문(된 상품) 인덱스
    PRODUCT_IDX             NUMBER          NOT NULL,   -- FK : 상품 인덱스
    MEMBER_IDX              NUMBER          NOT NULL,   -- FK : 고객 인덱스
    ORDERS_QUANTITY         NUMBER          NOT NULL,   -- 해당 상품 주문 수량
    ORDERS_STATUS           VARCHAR2(50),               -- 주문상태
    ORDERS_REGDATE          DATE            DEFAULT SYSDATE,    -- 주문 날짜
    
    CONSTRAINT ORDERS_PRODUCT_FK FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT(PRODUCT_IDX) ON DELETE CASCADE,
    CONSTRAINT ORDERS_MEMBER_FK FOREIGN KEY(MEMBER_IDX) REFERENCES MEMBER(MEMBER_IDX) ON DELETE CASCADE
);

CREATE TABLE REFUND (
    REFUND_IDX              NUMBER          DEFAULT REFUND_SEQ.NEXTVAL PRIMARY KEY,     -- 환불(신청된 상품) 인덱스
    ORDERS_IDX              NUMBER          NOT NULL,   -- FK : 주문(된 상품) 인덱스
    REFUND_REASON           VARCHAR2(2000)  NOT NULL,   -- 환불 사유
    REFUND_IMAGENAME        VARCHAR2(50),               -- 환불 신청 시 첨부한 이미지명
    REFUND_REGDATE          DATE            DEFAULT SYSDATE,    -- 환불 신청 날짜
    
    CONSTRAINT REFUND_ORDERS_FK FOREIGN KEY(ORDERS_IDX) REFERENCES ORDERS(ORDERS_IDX) ON DELETE CASCADE
);

COMMIT;
